import { item } from "./item";

export const itemList: { [id: number]: item } = {
    1: { id: 1, quantity: 0, name: 'potion', description: 'recupera 10 de vida', price: 10, type: 'consumable' },
    2: { id: 2, quantity: 0, name: 'wood sword', description: 'uma espada de madeira', price: 10, type: 'weapon' },
    3: { id: 3, quantity: 0, name: 'iron sword', description: 'uma espada de ferro', price: 20, type: 'weapon' },
    4: { id: 4, quantity: 0, name: 'steel sword', description: 'uma espada de aço', price: 30, type: 'weapon' },
    5: { id: 5, quantity: 0, name: 'wood shield', description: 'um escudo de madeira', price: 10, type: 'shield' },
    6: { id: 6, quantity: 0, name: 'iron shield', description: 'um escudo de ferro', price: 20, type: 'shield' },
    7: { id: 7, quantity: 0, name: 'steel shield', description: 'um escudo de aço', price: 30, type: 'shield' },
    8: { id: 8, quantity: 0, name: 'wood armor', description: 'uma armadura de madeira', price: 10, type: 'armor' },
    9: { id: 9, quantity: 0, name: 'iron armor', description: 'uma armadura de ferro', price: 20, type: 'armor' },
    10: { id: 10, quantity: 0, name: 'steel armor', description: 'uma armadura de aço', price: 30, type: 'armor' },
    11: { id: 11, quantity: 0, name: 'wood helmet', description: 'um capacete de madeira', price: 10, type: 'helmet' },
    12: { id: 12, quantity: 0, name: 'iron helmet', description: 'um capacete de ferro', price: 20, type: 'helmet' },
    13: { id: 13, quantity: 0, name: 'steel helmet', description: 'um capacete de aço', price: 30, type: 'helmet' },
    14: { id: 14, quantity: 0, name: 'wood boots', description: 'botas de madeira', price: 10, type: 'boots' },
    15: { id: 15, quantity: 0, name: 'iron boots', description: 'botas de ferro', price: 20, type: 'boots' },
    16: { id: 16, quantity: 0, name: 'steel boots', description: 'botas de aço', price: 30, type: 'boots' },
    17: { id: 17, quantity: 0, name: 'wood gloves', description: 'luvas de madeira', price: 10, type: 'gloves' },
    18: { id: 18, quantity: 0, name: 'iron gloves', description: 'luvas de ferro', price: 20, type: 'gloves' },
    19: { id: 19, quantity: 0, name: 'steel gloves', description: 'luvas de aço', price: 30, type: 'gloves' },
    20: { id: 20, quantity: 0, name: 'wood ring', description: 'um anel de madeira', price: 10, type: 'ring' },
    21: { id: 21, quantity: 0, name: 'iron ring', description: 'um anel de ferro', price: 20, type: 'ring' },
    22: { id: 22, quantity: 0, name: 'steel ring', description: 'um anel de aço', price: 30, type: 'ring' },
    23: { id: 23, quantity: 0, name: 'wood necklace', description: 'um colar de madeira', price: 10, type: 'necklace' },
    24: { id: 24, quantity: 0, name: 'iron necklace', description: 'um colar de ferro', price: 20, type: 'necklace' },
    25: { id: 25, quantity: 0, name: 'steel necklace', description: 'um colar de aço', price: 30, type: 'necklace' },
    26: { id: 26, quantity: 0, name: 'wood earring', description: 'um brinco de madeira', price: 10, type: 'earring' },
    27: { id: 27, quantity: 0, name: 'iron earring', description: 'um brinco de ferro', price: 20, type: 'earring' },
    28: { id: 28, quantity: 0, name: 'steel earring', description: 'um brinco de aço', price: 30, type: 'earring' },
    29: { id: 29, quantity: 0, name: 'wood belt', description: 'um cinto de madeira', price: 10, type: 'belt' },
    30: { id: 30, quantity: 0, name: 'iron belt', description: 'um cinto de ferro', price: 20, type: 'belt' },
    31: { id: 31, quantity: 0, name: 'steel belt', description: 'um cinto de aço', price: 30, type: 'belt' },
    32: { id: 32, quantity: 0, name: 'wood pants', description: 'uma calça de madeira', price: 10, type: 'pants' },
    33: { id: 33, quantity: 0, name: 'iron pants', description: 'uma calça de ferro', price: 20, type: 'pants' },
    34: { id: 34, quantity: 0, name: 'steel pants', description: 'uma calça de aço', price: 30, type: 'pants' },
}